services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: mamono-app
        container_name: mamono-app
        working_dir: /var/www/mamono
        volumes:
            - .:/var/www/mamono
        networks:
            - mamono-network
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: mamono-nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www/mamono
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - mamono-network

    db:
        image: mariadb:latest
        container_name: mamono-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - mamono-network

volumes:
    db-data:

networks:
    mamono-network:
        driver: bridge
